### ISSUE TITLE
Disabled 1.16.1

### ISSUE THREAD

**Issue by josiahkeeler** [Theguyhere0/compressed-cobblestone#1]
[22:57:08 INFO]: [CompressedCobble] Enabling CompressedCobble v1.3.0
[22:57:08 WARN]: Enabled plugin with unregistered PluginClassLoader CompressedCobble v1.3.0
[22:57:08 ERROR]: Error occurred while enabling CompressedCobble v1.3.0 (Is it up to date?)
java.lang.IllegalStateException: Duplicate recipe ignored with ID compressedcobble:cobblestone_x2
        at net.minecraft.server.v1_16_R1.CraftingManager.addRecipe(CraftingManager.java:78) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftShapelessRecipe.addToCraftingManager(CraftShapelessRecipe.java:47) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.addRecipe(CraftServer.java:1303) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.Bukkit.addRecipe(Bukkit.java:750) ~[patched_1.16.1.jar:git-Paper-130]
        at me.Theguyhere.CompressedCobble.Main.onEnable(Main.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-130]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[22:57:08 INFO]: [CompressedCobble] Disabling CompressedCobble v1.3.0

**Comment by techchrism** [comment]
Are you using PlugMan or some other means of reloading the plugin without starting and stopping the server (such as /reload)?
Part of the warning looks like it's from a plugin being disabled then re-enabled, see here: https://www.spigotmc.org/threads/enabled-plugin-with-unregistered-pluginclassloader.177886/page-2#post-3073288
If the issue is caused by reloading the plugin, the recipes can be removed when the plugin is disabled by referencing the key @Theguyhere0 (example: https://github.com/TheTechdoodle/gravity-gun/blob/d141aaea1e58fd24839ab0dbf863e5cee534e76d/src/main/java/com/darkender/plugins/gravitygun/GravityGun.java#L109)

**Comment by josiahkeeler** [comment]
This was all my fault. The plugin didn't load after the first restart, so I thought it was broken. After a second restart, it works perfectly. Thanks for your help!
