### ISSUE TITLE
Errors with other dimensions

### ISSUE THREAD

**Issue by josiahkeeler** [Theguyhere0/compressed-cobblestone#2]
Hello! I'm currently running into issues with other dimensions on a my server. When a player is in any dimensions besides the Overworld, the console gets spammed with error messages. Running Paper on 1.16.1. 

```
22:46:58 ERROR]: Could not pass event CreatureSpawnEvent to CompressedCobble v1.3.0
java.lang.IllegalArgumentException: Cannot measure distance between world and world_the_end
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.1.jar:git-Paper-130]
        at me.Theguyhere.CompressedCobble.MobSpawnEvents.lambda$0(MobSpawnEvents.java:76) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
        at me.Theguyhere.CompressedCobble.MobSpawnEvents.onSpawn(MobSpawnEvents.java:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor194.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-130]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:666) ~[patched_1.16.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:587) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.WorldServer.addEntity0(WorldServer.java:1153) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.WorldServer.addEntity(WorldServer.java:1061) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:253) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.SpawnerCreature.spawnMobs(SpawnerCreature.java:181) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.SpawnerCreature.a(SpawnerCreature.java:155) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:842) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:626) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:824) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer.tick(ChunkProviderServer.java:742) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:455) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1354) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-130]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Theguyhere0** [comment]
Thank you for reporting the bug. This has since been fixed in the v1.4.0 release. I tested this release on paper-135 and it worked fine. Let me know if the new version has bugs!

**Comment by Theguyhere0** [comment]
Whoops, can't close this myself

**Comment by josiahkeeler** [comment]
It might be a problem with Multiverse Core or Worldguard. Elitemobs_sewer_maze is a custom dimension with a few mob spawning Worldguard flags enabled. Updated to the latest Paper version.

```
[09:15:34 ERROR]: Could not pass event CreatureSpawnEvent to CompressedCobble v1.4.0
java.lang.IllegalArgumentException: Cannot measure distance between elitemobs_sewer_maze and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.1.jar:git-Paper-135]
        at me.Theguyhere.CompressedCobble.MobSpawnEvents.lambda$0(MobSpawnEvents.java:79) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
```

**Comment by Theguyhere0** [comment]
v1.4.1 should fix this bug but check with your own setup to make sure first

**Comment by josiahkeeler** [comment]
Wow! Thanks so much! What an active an amazing dev.
