### ISSUE TITLE
Could not pass event PlayerStatisticIncrementEvent to CompressedCobble v1.4.1

### ISSUE THREAD

**Issue by josiahkeeler** [Theguyhere0/compressed-cobblestone#4]
```
[16:08:19 ERROR]: Could not pass event PlayerStatisticIncrementEvent to CompressedCobble v1.4.1
java.lang.StringIndexOutOfBoundsException: begin 0, end 4, length 0
        at java.lang.String.checkBoundsBeginEnd(String.java:3756) ~[?:?]
        at java.lang.String.substring(String.java:1902) ~[?:?]
        at me.Theguyhere.CompressedCobble.MobSpawnEvents.playerStat(MobSpawnEvents.java:697) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor200.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-135]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:1542) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.StatisticManager.b(StatisticManager.java:19) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityPlayer.a(EntityPlayer.java:1440) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityHuman.b(EntityHuman.java:1369) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityHuman.a(EntityHuman.java:1361) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityHuman.tick(EntityHuman.java:175) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.EntityPlayer.playerTick(EntityPlayer.java:504) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1592) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.NetworkManager.handleDisconnection(NetworkManager.java:481) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:162) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1385) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:832) [?:?]

```

**Comment by josiahkeeler** [comment]
High tick usage too if CC mobs are left loaded too long. 
![Screenshot_20200816_161355](https://user-images.githubusercontent.com/29555490/90346155-7f9c4100-dfdb-11ea-974f-0ea008b4799d.png)

**Comment by Theguyhere0** [comment]
Hey @josiahkeeler I need a bit more context for what the issue was. Do you know how to reproduce it? What were players doing when this happened? Was there a noticeable mechanic issue in-game or just a console error (which I still need to fix for sure)?

Also yeah, a lot of my event listeners are probably not optimal, so that would be on a list of things to improve.

**Comment by Theguyhere0** [comment]
I think I know what the issue is. Probably has to do with checking other items that also have item lore. I've reworked the code in the next update to fix this, so once it's out please check to see if it fixes the issue.

**Comment by josiahkeeler** [comment]
One player without any CC gear went AFK in safe spot. Another player with max CC gear entered the area and a few skeletons spawned to attack him. He left the server, but since the skeletons were still in loaded chunks they just stayed stayed in the area for about 8 hrs.  I joined the server to check the TPS dip and found the skeletons and killed them.
